/*
 *  codeTbl.c
 *    「実体参照→代替文字列変換テーブル」の実体
 *
 * History:
 * $Log: /comm/xmlRPC/codeTbl.c $
 * 
 * 1     09/05/14 3:46 tsupo
 * (1) ビルド環境のディレクトリ構造を整理
 * (2) VSSサーバ拠点を変更
 * 
 * 1     06/02/27 21:03 Tsujimura543
 * 「実体参照→代替文字列変換テーブル」の実体を codeTbl.c として分離独立
 */

#include <stdlib.h>
#include "codeTbl.h"

#ifndef	lint
static char	*rcs_id =
"$Header: /comm/xmlRPC/codeTbl.c 1     09/05/14 3:46 tsupo $";
#endif

struct replaceTable entity_code_repTbl[] = {
    { "&amp;",     "&",     '&'        },
    { "&lt;",      "<",     '<'        },
    { "&gt;",      ">",     '>'        },
    { "&quot;",    "\"",    '"'        },
    { "&nbsp;",    " ",     ' '        },
    { "&brvbar;",  "|",     '|'        },
    { "&circ;",    "^",     '^'        },
    { "&tilde;",   "~",     '~'        },
    { "&iexcl;",   "!",     CD_IEXCL   },
    { "&iquest;",  "?",     CD_IQUEST  },
    { "&yen;",     "￥",    CD_YEN     },
    { "&cent;",    " ￠",   CD_CENT    },
    { "&pound;",   "￡" ,   CD_POUND   },
    { "&curren;",  " " ,    CD_CURREN  },
    { "&copy;",    "(c)",   CD_COPY    },
    { "&reg;",     "(R)",   CD_REG     },
    { "&trade;",   "TM",    CD_TRADE   },
    { "&sect;",    "§",    CD_SECT    },
    { "&laquo;",   "≪",    CD_LAQUO   },
    { "&raquo;",   "≫",    CD_RAQUO   },
    { "&not;",     "￢",    CD_NOT     },
    { "&macr;",    "￣",    CD_MACR    },
    { "&deg;",     "°",    CD_DEG     },
    { "&plusmn;",  "±",    CD_PLUSMN  },
    { "&acute;",   "´",    CD_ACUTE   },
    { "&micro;",   "μ",    CD_MICRO   },
    { "&para;",    "¶",    CD_PARA    },
    { "&midot;",   "・",    CD_MIDDOT  },
    { "&uml;",     "¨",    CD_UML     },
    { "&cedil;",   "，",    CD_CEDIL   },
    { "&Agrave;",  "A",     CD_AGRAVE  },
    { "&Aacute;",  "A",     CD_AACUTE  },
    { "&Acirc;",   "A",     CD_ACIRC   },
    { "&Atilde;",  "A",     CD_ATILDE  },
    { "&Auml;",    "A",     CD_AUML    },
    { "&Aring;",   "Å",    CD_ARING   },
    { "&AElig;",   "AE",    CD_AELIG   },
    { "&Ccedil;",  "C",     CD_CCEDIL  },
    { "&Egrave;",  "E",     CD_EGRAVE  },
    { "&Eacute;",  "E",     CD_EACUTE  },
    { "&Ecirc;",   "E",     CD_ECIRC   },
    { "&Euml;",    "E",     CD_EUML    },
    { "&Igrave;",  "I",     CD_IGRAVE  },
    { "&Iacute;",  "I",     CD_IACUTE  },
    { "&Icirc;",   "I",     CD_ICIRC   },
    { "&Iuml;",    "I",     CD_IUML    },
    { "&Ntilde;",  "N",     CD_NTILDE  },
    { "&Ograve;",  "O",     CD_OGRAVE  },
    { "&Oacute;",  "O",     CD_OACUTE  },
    { "&Ocirc;",   "O",     CD_OCIRC   },
    { "&Otilde;",  "O",     CD_OTILDE  },
    { "&Ouml;",    "O",     CD_OUML    },
    { "&Oslash;",  "O",     CD_OSLASH  },
    { "&Ugrave;",  "U",     CD_UGRAVE  },
    { "&Uacute;",  "U",     CD_UACUTE  },
    { "&Ucirc;",   "U",     CD_UCIRC   },
    { "&Uuml;",    "U",     CD_UUML    },
    { "&agrave;",  "a",     CD_AGRAVEs },
    { "&aacute;",  "a",     CD_AACUTEs },
    { "&acirc;",   "a",     CD_ACIRCs  },
    { "&atilde;",  "a",     CD_ATILDEs },
    { "&auml;",    "a",     CD_AUMLs   },
    { "&aring;",   "a",     CD_ARINGs  },
    { "&aElig;",   "ae",    CD_AELIGs  },
    { "&ccedil;",  "c",     CD_CCEDILs },
    { "&egrave;",  "e",     CD_EGRAVEs },
    { "&eacute;",  "e",     CD_EACUTEs },
    { "&ecirc;",   "e",     CD_ECIRCs  },
    { "&euml;",    "e",     CD_EUMLs   },
    { "&igrave;",  "i",     CD_IGRAVEs },
    { "&iacute;",  "i",     CD_IACUTEs },
    { "&icirc;",   "i",     CD_ICIRCs  },
    { "&iuml;",    "i",     CD_IUMLs   },
    { "&ntilde;",  "n",     CD_NTILDEs },
    { "&ograve;",  "o",     CD_OGRAVEs },
    { "&oacute;",  "o",     CD_OACUTEs },
    { "&ocirc;",   "o",     CD_OCIRCs  },
    { "&otilde;",  "o",     CD_OTILDEs },
    { "&ouml;",    "o",     CD_OUMLs   },
    { "&oslash;",  "o",     CD_OSLASHs },
    { "&ugrave;",  "u",     CD_UGRAVEs },
    { "&uacute;",  "u",     CD_UACUTEs },
    { "&ucirc;",   "u",     CD_UCIRCs  },
    { "&uuml;",    "u",     CD_UUMLs   },
    { "&yuml;",    "y",     CD_YUMLs   },
    { "&shy;",     "-",     -1         },

    { "&times;",   "×",    CD_TIMES   },
    { "&divide;",  "÷",    CD_DIVIDE  },
    { "&ne;",      "≠",    CD_NE      },
    { "&cong;",    "≒",    CD_CONG    },
    { "&asymp;",   "≒",    CD_ASYMP   },
    { "&equiv;",   "≡",    CD_EQUIV   },
    { "&le;",      "≦",    -1         },
    { "&ge;",      "≧",    -1         },
    { "&sub;",     "⊂",    CD_SUB     },
    { "&sup;",     "⊃",    CD_SUP     },
    { "&sube;",    "⊆",    CD_SUBE    },
    { "&supe;",    "⊇",    CD_SUPE    },
    { "&minus;",   "－",    CD_MINUS   },
    { "&perp;",    "⊥",    CD_PERP    },
    { "&sup1;",    "1",     CD_SUP1    },
    { "&sup2;",    "2",     CD_SUP2    },
    { "&sup3;",    "3",     CD_SUP3    },
    { "&ordf;",    "a",     CD_ORDF    },
    { "&ordm;",    "o",     CD_ORDM    },
    { "&frac14;",  "1/4",   CD_FRAC14  },
    { "&frac12;",  "1/2",   CD_FRAC12  },
    { "&frac34;",  "3/4",   CD_FRAC34  },
    { "&szlig;",   "ss",    CD_SZLIG   },

    { "&Alpha;",   "Α",    -1         },
    { "&Beta;",    "Β",    -1         },
    { "&Gamma;",   "Γ",    -1         },
    { "&Delta;",   "Δ",    -1         },
    { "&Epsilon;", "Ε",    -1         },
    { "&Zeta;",    "Ζ",    -1         },
    { "&Eta;",     "Η",    -1         },
    { "&Theta;",   "Θ",    -1         },
    { "&Iota;",    "Ι",    -1         },
    { "&Kappa;",   "Κ",    -1         },
    { "&Lambda;",  "Λ",    -1         },
    { "&Mu;",      "Μ",    -1         },
    { "&Nu;",      "Ν",    -1         },
    { "&Xi;",      "Ξ",    -1         },
    { "&Omicron;", "Ο",    -1         },
    { "&Pi;",      "Π",    -1         },
    { "&Rho;",     "Ρ",    -1         },
    { "&Sigma;",   "Σ",    -1         },
    { "&Tau;",     "Τ",    -1         },
    { "&Upsilon;", "Υ",    -1         },
    { "&Phi;",     "Φ",    -1         },
    { "&Chi;",     "Χ",    -1         },
    { "&Psi;",     "Ψ",    -1         },
    { "&Omega;",   "Ω",    -1         },
    { "&alpha;",   "α",    -1         },
    { "&beta;",    "β",    -1         },
    { "&gamma;",   "γ",    -1         },
    { "&delta;",   "δ",    -1         },
    { "&epsilon;", "ε",    -1         },
    { "&zeta;",    "ζ",    -1         },
    { "&eta;",     "η",    -1         },
    { "&theta;",   "θ",    -1         },
    { "&iota;",    "ι",    -1         },
    { "&kappa;",   "κ",    -1         },
    { "&lambda;",  "λ",    -1         },
    { "&mu;",      "μ",    -1         },
    { "&nu;",      "ν",    -1         },
    { "&xi;",      "ξ",    -1         },
    { "&omicron;", "ο",    -1         },
    { "&pi;",      "π",    -1         },
    { "&rho;",     "ρ",    -1         },
    { "&sigmaf;",  "σ",    CD_SIGMAF  },
    { "&sigma;",   "σ",    -1         },
    { "&tau;",     "τ",    -1         },
    { "&upsilon;", "υ",    -1         },
    { "&phi;",     "φ",    -1         },
    { "&chi;",     "χ",    -1         },
    { "&psi;",     "ψ",    -1         },
    { "&omega;",   "ω",    -1         },

    { "&ndash;",   "‐",    -1         },
    { "&mdash;",   "―",    -1         },
    { "&lsquo;",   "‘",    -1         },
    { "&rsquo;",   "’",    -1         },
    { "&ldquo;",   "“",    -1         },
    { "&rdquo;",   "”",    -1         },
    { "&dagger;",  "†",    -1         },
    { "&Dagger;",  "‡",    -1         },
    { "&bull;",    "・",    -1         },
    { "&hellip;",  "…",    -1         },
    { "&permil;",  "‰",    -1         },
    { "&prime;",   "′",    -1         },
    { "&Prime;",   "″",    -1         },
    { "&larr;",    "←",    -1         },
    { "&uarr;",    "↑",    -1         },
    { "&rarr;",    "→",    -1         },
    { "&darr;",    "↓",    -1         },
    { "&rArr;",    "⇒",    -1         },
    { "&hArr;",    "⇔",    -1         },
    { "&forall;",  "∀",    -1         },
    { "&part;",    "∂",    -1         },
    { "&exist;",   "∃",    -1         },
    { "&nabla;",   "∇",    -1         },
    { "&isin;",    "∈",    -1         },
    { "&ni;",      "∋",    -1         },
    { "&sum;",     "∑",    -1         },
    { "&radic;",   "√",    -1         },
    { "&prop;",    "∝",    -1         },
    { "&infin;",   "∞",    -1         },
    { "&ang;",     "∠",    -1         },
    { "&and;",     "∧",    -1         },
    { "&or;",      "∨",    -1         },
    { "&cap;",     "∩",    -1         },
    { "&cup;",     "∪",    -1         },
    { "&int;",     "∫",    -1         },
    { "&there4;",  "∴",    -1         },

    { "&OElig;",   "O",     CD_OELIG   },
    { "&oelig;",   "o",     CD_OELIGs  },
    { "&Yuml;",    "y",     CD_YUML    },
    { "&Scaron;",  "S",     CD_SCARON  },
    { "&scaron;",  "s",     CD_SCARONs },
    { "&fnof;",    "f",     CD_FNOF    },
    { "&thetasym;","θ",    -1         },
    { "&upsih;",   "Υ" ,   -1         },
    { "&piv;",     "ω",    -1         },

    { "&ensp;",    " ",     -1         },
    { "&emsp;",    " ",     -1         },
    { "&thinsp;",  " ",     -1         },
    { "&zwnj;",    " ",     -1         },
    { "&zwj;",     " ",     -1         },
    { "&lrm;",     " ",     -1         },
    { "&rlm;",     " ",     -1         },

    { "&sbquo;",   ",",     CD_SBQUO   },
    { "&bdquo;",   "〟",    CD_BDQUO   },
    { "&lsaquo;",  "〈",    CD_LSAQUO  },
    { "&rsaquo;",  " 〉",   CD_RSAQUO  },
    { "&oline;",   "￣",    CD_OLINE   },
    { "&frasl;",   "/",     CD_FRASL   },
    { "&euro;",    "euro",  CD_EURO    },
    { "&image;",   "I",     -1         },
    { "&weierp;",  "P",     -1         },
    { "&real;",    "R",     -1         },
    { "&alefsym;", "A0",    -1         },
    { "&harr;",    "←→",  CD_HARR    },
    { "&crarr;", "[Enter]", -1         },
    { "&lArr;",    "←",    -1         },
    { "&uArr;",    "↑",    -1         },
    { "&dArr;",    "↓",    -1         },
    { "&empty;",   "(空)",  -1         },
    { "&notin;",   "?",     -1         },
    { "&prod;",    "П",    -1         },
    { "&lowast;",  "*",     -1         },
    { "&sim;",     "~",     CD_SIM     },
    { "&nsub;",    "?",     -1         },
    { "&oplus;",   "(+)",   CD_OPLUS   },
    { "&otimes;",  "(X)",   -1         },
    { "&sdot;",    ".",     -1         },
    { "&lceil;",   "┌",    -1         },
    { "&rceil;",   "┐",    -1         },
    { "&lfloor;",  "└ ",   -1         },
    { "&rfloor;",  "┘",    -1         },
    { "&lang;",    "〈",    -1         },
    { "&rang;",    "〉",    -1         },
    { "&loz;",     "◇",    CD_LOZ     },
    { "&spades;",  "S",     CD_SPADES  },
    { "&clubs;",   "C",     CD_CLUBS   },
    { "&hearts;",  "H",     CD_HEARTS  },
    { "&diams;",   "◆",    CD_DIAMS   },
    { NULL,        NULL,    -1         }
};
